modLoader="javafml"
loaderVersion="[1,)"
license="MIT (CC BY-NC-SA 4.0 for some Assets)"
issueTrackerURL="https://github.com/quiqueck/bclib/issues"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="BCLib"
description="A library for BetterX team mods"
authors="Quiqueck, paulevs, Bulldog83, Raijin"
displayURL="https://modrinth.com/mod/bclib"
logoFile="assets/bclib/icon.png"

[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="wunderlib"
mandatory=true
versionRange="[21.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="wover"
mandatory=true
versionRange="[21.0,)"
ordering="NONE"
side="BOTH"


[[mixins]]
config="ui.mixins.client.json"

[[mixins]]
config="bclib.mixins.common.json"

[[mixins]]
config="bclib.mixins.client.json"
